# Generated by Django 3.2.7 on 2021-09-24 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210921_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='birthdate',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Больница', to='main.hospital', verbose_name='Больница'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nurse', verbose_name='Медсестра'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='position',
            field=models.CharField(choices=[('therapist', 'Терапевт'), ('surgeon', 'Хирург')], default='therapist', max_length=255, verbose_name='Терапевт/Хирург'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Врач', to='main.maindoctor', verbose_name='Врачи'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nurse', verbose_name='Медсёстры'),
        ),
        migrations.AlterField(
            model_name='maindoctor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='birthdate',
            field=models.DateField(verbose_name='Дата Рождения'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hospital', verbose_name='Больница'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nurse', verbose_name='Медсестра'),
        ),
    ]
