# Generated by Django 3.2.7 on 2021-09-28 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_hospital_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Врач', to='main.doctor', verbose_name='Врачи'),
        ),
    ]
